apiVersion: networking.k8s.io/v1beta1   
kind: Ingress
metadata:
  name: flask-ingress
spec:
  rules:
  - host: augnito.example.com    # we have to add the host in DNS config file. (Local /etc/hosts)
    http:
      paths:
      - path: /
        pathType:
        backend:
          serviceName: flask-service
          servicePort: http